---
title: "Classification Analysis"
author: "Harry Zhong"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
source("scripts/packages.R")
```

```{r}
track_features <- read_csv("data/feature_data/track_features.csv")

full_track_features <- read_csv("data/feature_data/full_track_features.csv") %>%
  rename(trackName = "track_name",
         artistName = "artist_name",
         trackID = "track_uri")

kaggle_dataset <- read_csv("data/feature_data/kaggle_dataset.csv") %>%
  rename(trackName = "track_name",
         artistName = "artists",
         trackID = "track_id",
         index = 1) %>%
  select(-album_name,
         -popularity,
         -explicit, 
         -index, 
         -track_genre) %>%
  distinct(trackName, .keep_all = TRUE)
```

```{r}
feature_matrix <- full_track_features %>%
  mutate(track_artist = paste(trackName, artistName, sep = " - ")) %>%
  select(-trackName, -artistName) %>%
  column_to_rownames(var = "track_artist") %>%
  select(-trackID,
         -key,
         -mode,
         -time_signature) %>%
  scale()
```

```{r}
kmeans_select_features <- function(n, data, nstart, itermax) {
  n_factors <- n
  
  comb_n <- data %>%
    colnames() %>%
    combn(n_factors, simplify = FALSE)
  
  old_cols <- seq(1, n_factors)
  new_cols <- paste0("factor_", seq(1, n_factors))
  
  new_cols_sym <- syms(new_cols)
  
  factor_combinations_n <- do.call(rbind.data.frame, comb_n) %>%
    rename_with(~new_cols, all_of(old_cols)) %>%
    mutate(factors = pmap(list(!!!new_cols_sym), c)) %>%
    select(-(!!new_cols)) %>%
    mutate(data = map(factors,
                      ~data %>%
                        as.data.frame() %>%
                        select(all_of(.x)))) %>%
    mutate(n_clusters = map(data,
                            ~fviz_nbclust(.x, 
                                          kmeans, 
                                          nstart = nstart, 
                                          iter.max = itermax)[["data"]] %>%
                              slice(which.max(y)) %>%
                              select(clusters) %>%
                              as.numeric(),
                            .progress = paste("Finding optimal n_clusters:", 
                                              n_factors, 
                                              "factors")) %>%
             as.numeric()) %>% 
    mutate(km = map2(data,
                     n_clusters,
                     ~kmeans(.x, 
                             .y, 
                             nstart = nstart, 
                             iter.max = itermax,
                             algorithm = "MacQueen"),
                     .progress = paste("Calculating kmeans:", 
                                       n_factors, 
                                       "factors"))) %>%
    mutate(total_withinss = map(km,
                                ~.x$tot.withinss) %>%
             as.numeric(),
           bsstssRatio = map(km,
                             ~.x$betweenss/.x$totss) %>%
             as.numeric()) %>%
    mutate(km_plot = map2(km,
                          data,
                          ~fviz_cluster(.x,
                                        data = .y,
                                        geom = "point",
                                        ellipse.type = "convex",
                                        ggtheme = theme_bw()))) %>%
    arrange(desc(bsstssRatio))  
  
  return(factor_combinations_n)
}
```

```{r}
set.seed(2687)

kmeans_2fact <- kmeans_select_features(2, feature_matrix, 25, 1000)

for (i in 1:20) {
  kmeans_2fact %>%
    slice(i) %>%
    pull(km_plot) %>%
    print()
}
```

```{r}
set.seed(2687)

cl <- makeCluster(detectCores())
registerDoParallel(cl)

start_time <- Sys.time()

kmeans_nfact <- foreach(n = seq(2, ncol(feature_matrix)),
                                 .packages = c("tidyverse",
                                               "cluster",
                                               "factoextra",
                                               "rlang"),
                                 .combine = bind_rows) %dopar% {
                                   kmeans_select_features(n, feature_matrix, 25, 1000)
                                 } %>% 
  arrange(desc(bsstssRatio))

end_time <- Sys.time()
time_taken <- end_time - start_time

stopCluster(cl)

for (i in 1:20) {
  kmeans_nfact %>%
    slice(i) %>%
    pull(km_plot) %>%
    print()
}
```

```{r}
kmeans_nfact_save <- kmeans_nfact %>%
  select(-data) %>%
  slice(1:20)

save(kmeans_nfact_save, 
     file = "data/R_data/kmeans_nfact.RData",
     compress = "xz")
```

```{r}
load("data/R_data/kmeans_nfact.RData")
kmeans_nfact <- kmeans_nfact_save
```

```{r}
km_index <- 5

kmeans_clusters <- kmeans_nfact %>%
  slice(km_index) %>%
  pull(km) %>%
  pluck(1) %>%
  pluck("centers") %>%
  as.data.frame() %>%
  rownames_to_column("cluster") %>%
  mutate(cluster = paste0("Cluster ", cluster))

cluster_top_tracks <- kmeans_nfact %>%
  slice(km_index) %>%
  pull(km) %>%
  pluck(1) %>%
  pluck("cluster") %>%
  as.data.frame() %>%
  rownames_to_column("track_artist") %>%
  rename(cluster = 2) %>% 
  mutate(cluster = paste0("Cluster ", cluster)) %>%
  left_join(full_streaming_history %>%
              select(track_name,
                     artist_name,
                     ms_played) %>%
              na.omit() %>%
              group_by(track_name,
                       artist_name) %>%
              summarise(hours_listened = sum(ms_played/(1000*60))) %>%
              mutate(track_artist = paste(track_name,
                                          artist_name,
                                          sep = " - ")),
            .,
            by = "track_artist") %>%
  select(-track_artist) %>%
  group_by(cluster) %>%
  slice_max(hours_listened, n = 10) %>%
  ungroup() %>%
  select(cluster,
         everything())

track_clusters <- kmeans_nfact %>%
  slice(km_index) %>%
  pull(km) %>%
  pluck(1) %>%
  pluck("cluster") %>%
  as.data.frame() %>%
  rownames_to_column("track_artist") %>%
  rename(cluster = 2) %>% 
  mutate(cluster = paste0("Cluster ", cluster)) %>%
  left_join(full_streaming_history %>%
              select(track_name,
                     artist_name) %>%
              na.omit() %>%
              distinct() %>%
              mutate(track_artist = paste(track_name,
                                          artist_name,
                                          sep = " - ")),
            .,
            by = "track_artist") %>%
  select(-track_artist) %>%
  arrange(artist_name,
          track_name)

artist_clusters <- track_clusters %>%
  group_by(artist_name,
           cluster) %>%
  summarise(count = n())
```
