---
title: "Data Extraction"
author: "Harry Zhong"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
source("packages.R")
```

Extract streaming history data from .json files.

```{r}
for (i in seq(0,2)) {
  assign(paste0("streaming_history_", i),
         fromJSON(
           paste0("data/StreamingHistory_music_", i, ".json")
           ) %>%
           as.data.frame()
         )
}

streaming_history <- bind_rows(streaming_history_0,
                               streaming_history_1,
                               streaming_history_2
                               ) %>%
  mutate(endTime = endTime %>%
           substring(1, 7) %>%
           paste0("-01") %>%
           ymd()) %>%
  rename(month = endTime)
```

Get Spotify token from API.

```{r}
source("generate_token.R")
```

Make functions to get artist genres via artist id.

```{r}
search_artist <- function(artist_name) {
  url <- "https://api.spotify.com/v1/search"
  response <- GET(url, add_headers(Authorization = paste("Bearer", spotify_token)), query = list(q = artist_name, type = "artist", limit = 1))
  content(response)$artists$items[[1]]$id
}

get_genres <- function(artist_id) {
  url <- paste0("https://api.spotify.com/v1/artists/", artist_id)
  response <- GET(url, add_headers(Authorization = paste("Bearer", spotify_token)))
  content(response)$genres
}
```

Match artists to genres using API functions.

```{r}
unique_artists <- streaming_history %>% 
  select(artistName) %>%
  distinct() %>%
  mutate(
    artistID = map(artistName,
                   ~search_artist(.x),
                   .progress = "Searching Artist IDs"
                   )
  ) %>%
  mutate(
    genre = map(artistID,
                ~get_genres(.x),
                .progress = "Getting Artist Genres"
                )
  )
```

Make functions to get audio features via track id.

```{r}
search_track <- function(track_name, artist_name) {
  #build in delay to not get rate limited
  Sys.sleep(0.4)
  track_name <- track_name %>%
    str_replace_all("[^a-zA-Z\\s]", "") %>%
    trimws() %>%
    str_replace_all(" ", "%20")
  artist_name <- artist_name %>%
    str_replace_all("[^a-zA-Z\\s]", "") %>%
    trimws() %>%
    str_replace_all(" ", "%20")
  url <- paste0("https://api.spotify.com/v1/search?q=track:", 
                track_name, 
                "%20artist:", 
                artist_name, 
                "&type=track&limit=1")
  response <- GET(url, add_headers(Authorization = paste("Bearer", spotify_token)))
  fromJSON(content(response, "text", encoding = "UTF-8"))$tracks$items$id
}

get_audio_features <- function(track_id) {
  #build in delay to not get rate limited
  Sys.sleep(0.4)
  url = paste0("https://api.spotify.com/v1/audio-features/", track_id)
  response <- GET(url, add_headers(Authorization = paste("Bearer", spotify_token)))
  fromJSON(content(response, "text", encoding = "UTF-8"))
}
```

Match tracks to stuff using API functions.

```{r}
unique_tracks <- streaming_history %>%
  select(artistName, trackName) %>%
  distinct() %>%
  mutate(
    trackID = map2(artistName,
                   trackName,
                   ~search_track(.y, .x),
                   .progress = "Searching Track IDs"
                   )
  ) %>%
  mutate(
    audio_features = map(trackID,
                         ~get_audio_features(.x),
                         .progress = "Getting Audio Features"
                         )
  )

source("generate_token.R")

unique_tracks_2 <- unique_tracks %>%
  filter(map_lgl(audio_features, ~"error" %in% names(.x))) %>% 
  mutate(
    audio_features = map(trackID,
                         ~get_audio_features(.x),
                         .progress = "Getting Audio Features"
                         )
  )

unique_tracks_combined <- bind_rows(unique_tracks %>%
                                      filter(!map_lgl(audio_features, ~"error" %in% names(.x))),
                                    unique_tracks_2)

unique_tracks_split <- unique_tracks_combined %>%
  filter(trackID != "NULL") %>%
  mutate(label = map(audio_features, names)) %>%
  unnest(c(audio_features, label)) %>%
  mutate(audio_features = unlist(audio_features),
         trackID = unlist(trackID)) %>%
  pivot_wider(names_from = label, values_from = audio_features) %>%
  select(artistName,
         trackName,
         trackID,
         danceability,
         energy,
         key,
         loudness,
         mode,
         speechiness,
         acousticness,
         instrumentalness,
         liveness,
         valence,
         tempo,
         duration_ms,
         time_signature) %>%
  mutate(danceability = as.numeric(danceability),
         energy = as.numeric(energy),
         key = as.numeric(key),
         loudness = as.numeric(loudness),
         mode = as.numeric(mode),
         speechiness = as.numeric(speechiness),
         acousticness = as.numeric(acousticness),
         instrumentalness = as.numeric(instrumentalness),
         liveness = as.numeric(liveness),
         valence = as.numeric(valence),
         tempo = as.numeric(tempo),
         duration_ms = as.numeric(duration_ms),
         time_signature = as.numeric(time_signature))

write.csv(unique_tracks_split, file = "track_features.csv", row.names = FALSE)
```
